services:
  nest:
    build:
      dockerfile: .docker/nest/Dockerfile
    restart: unless-stopped
    ports:
      - ${NEST_PORT}:3000
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASS: pass
      DB_NAME: postgres
      DB_LOGS: ${DB_LOGS}
      ENV_NAME: ${ENV_NAME}
    volumes:
      - ./nest:/home/node/app
    depends_on:
      - db

  db:
    image: postgres:16.1-alpine3.19
    restart: always
    ports:
      - ${DB_PORT}:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: postgres

  angular:
    build:
      dockerfile: .docker/angular/Dockerfile
    container_name: angular
    restart: unless-stopped
    ports:
      - ${NG_PORT}:4200
    volumes:
      - ./angular:/home/node/app
